[project]
name = "kawaboard"
version = "0.1.1"
description = "Kawaii drawing board with utilities!"
readme = "README.md"
authors = [
    { name = "Ivan Chetchasov", email = "vi.is.chapmann@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "capstone>=5.0.9",
    "eel>=0.18.2",
    "keystone>=29.0.2",
    "keystone-engine>=0.9.2",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.11",
]

[project.scripts]
kawaboard = "kawaboard:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
